### ISSUE TITLE
Errors on default Ubuntu installation

### ISSUE THREAD

**Issue by wieset** [levingerdes/minimal-vimrc#1]
The following errors appear on a default Ubuntu 18.04 installation without clang format. Could you create a separate branch without lines 42 ff?

```
Error detected while processing VimEnter Auto commands for "*":
E492: Not an editor command: PlugInstall --sync | source $MYVIMRC
```

```
Error detected while processing /home/marta/.vimrc:
line   49:
E117: Unknown function: plug#begin
line   50:
E492: Not an editor command: Plug 'chiel92/vim-autoformat'
line   51:
E117: Unknown function: plug#end
```

**Comment by levingerdes** [comment]
The error you've encountered most likely stems from the fact that the default Ubuntu installations don't have *curl* preinstalled, and this is used during Plug's install phase. So when exiting vim you should have seen something in the lines of *command not found: curl*. The vim-autoformat Plug does not break vim even if clang-format is not installed, it has a fallback mode for indentation.

I agree though that it's not *minimal* anymore to install a plugin manager. I'll move it into a separate branch as suggested.

**Comment by wieset** [comment]
Great, good to know. Thanks a lot :)

**Comment by levingerdes** [comment]
Actually, I think that might be overkill. I'll just leave it in comments.
